language: generic
sudo: required
dist: trusty

env:
  - QGIS_REPO=http://qgis.org/debian-ltr
  - QGIS_REPO=http://qgis.org/debian

addons: 
  apt: 
    packages: 
      - python-software-properties 

-before_install:
  - sudo apt-get -qq -y update

install:
  - sudo add-apt-repository ${QGIS_REPO}
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis xvfb
  - sudo -H pip install --upgrade pip
  - sudo -H pip install nose
  - sudo -H pip install rednose

before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - QGIS_DEBUG=0 xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -s --nologcapture -A 'not slow' -v --rednose --verbose 

notifications:
  email:
    - tom.chadwin@nnpa.org.uk
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always